
@baseUrl = https://app-poc-gc-6.azurewebsites.net

###
POST {{baseUrl}}/consumers
content-type: application/json


{
    "StringSizeInKB": 50, 
    "NumberOfString": 100
}

###
GET {{baseUrl}}/info
###
GET {{baseUrl}}/collect
###
GET {{baseUrl}}/_health





###
GET https://app-poc-gc-1.azurewebsites.net/collect
###
GET https://app-poc-gc-2.azurewebsites.net/collect
###
GET https://app-poc-gc-3.azurewebsites.net/collect
###
GET https://app-poc-gc-4.azurewebsites.net/collect
###
GET https://app-poc-gc-5.azurewebsites.net/collect
###
GET https://app-poc-gc-6.azurewebsites.net/collect
